# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_Bhumesh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test_Bhumesh
pod 'Alamofire', '~> 4.0'
pod 'SDWebImage'
  target 'Test_BhumeshTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test_BhumeshUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
